---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Candy Server"
paths:
  /buy_candy:
    post:
      operationId: "buyCandy"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "order"
          description: "summary of the candy order"
          required: false
          schema:
            $ref: "#/definitions/order"
          x-exportParamName: "Order"
      responses:
        "201":
          description: "purchase succesful"
          schema:
            $ref: "#/definitions/inline_response_201"
        "400":
          description: "some error in input data"
          schema:
            $ref: "#/definitions/inline_response_400"
        "402":
          description: "not enough money"
          schema:
            $ref: "#/definitions/inline_response_400"
definitions:
  inline_response_201:
    type: "object"
    properties:
      thanks:
        type: "string"
      change:
        type: "integer"
    example:
      thanks: "thanks"
      change: 0
  order:
    type: "object"
    required:
      - "candyCount"
      - "candyType"
      - "money"
    properties:
      money:
        type: "integer"
        description: "amount of money put into vending machine"
      candyType:
        type: "string"
        description: "kind of candy"
      candyCount:
        type: "integer"
        description: "number of candy"
  inline_response_400:
    type: "object"
    properties:
      error:
        type: "string"
